clusterName: ${CLUSTER_NAME}
splunkObservability:
  realm: ${REALM}
  accessToken: ${SPLUNK_OBSERVABILITY_ACCESS_TOKEN}

agent:
  config:
    exporters:
      debug:
        verbosity: detailed
    processors:
      transform/frontend-available:
        error_mode: ignore
        metric_statements:
          - error_mode: propagate
            statements:
              - replace_all_patterns(resource.attributes, "value", "frontend", "available-funds-check")
        trace_statements:
          - error_mode: propagate
            statements:
              - replace_all_patterns(resource.attributes, "value", "frontend", "available-funds-check")
              - replace_all_patterns(span.attributes, "value", "frontend", "available-funds-check")
              - replace_pattern(span.name, "frontend", "available-funds-check")
      transform/cart-checkdeposit:
        error_mode: ignore
        metric_statements:
          - error_mode: propagate
            statements:
              - replace_all_patterns(resource.attributes, "value", "cartservice", "funds-deposit")
        trace_statements:
          - error_mode: propagate
            statements:
              - replace_all_patterns(resource.attributes, "value", "cartservice", "funds-deposit")
      transform/checkout-compliance:
        error_mode: ignore
        metric_statements:
          - error_mode: propagate
            statements:
              - replace_all_patterns(resource.attributes, "value", "checkoutservice", "compliance-check")
        trace_statements:
          - error_mode: propagate
            statements:
              - replace_all_patterns(resource.attributes, "value", "checkoutservice", "compliance-check")
      transform/payment-symbolcheck:
        error_mode: ignore
        metric_statements:
          - error_mode: propagate
            statements:
              - replace_all_patterns(resource.attributes, "value", "paymentservice", "wire-transfer-service")
        trace_statements:
          - error_mode: propagate
            statements:
              - replace_all_patterns(resource.attributes, "value", "paymentservice", "wire-transfer-service")
      transform/productcatalog-validation:
        error_mode: ignore
        metric_statements:
          - error_mode: propagate
            statements:
              - replace_all_patterns(resource.attributes, "value", "productcatalogservice", "validation-service")
        trace_statements:
          - error_mode: propagate
            statements:
              - replace_all_patterns(resource.attributes, "value", "productcatalogservice", "validation-service")
      transform/shipping-credit:
        error_mode: ignore
        metric_statements:
          - error_mode: propagate
            statements:
              - replace_all_patterns(resource.attributes, "value", "shippingservice", "credit-card-service")
        trace_statements:
          - error_mode: propagate
            statements:
              - replace_all_patterns(resource.attributes, "value", "shippingservice", "credit-card-service")
      transform/email-newacct:
        error_mode: ignore
        metric_statements:
          - error_mode: propagate
            statements:
              - replace_all_patterns(resource.attributes, "value", "emailservice", "new-account-service")
        trace_statements:
          - error_mode: propagate
            statements:
              - replace_all_patterns(resource.attributes, "value", "emailservice", "new-account-service")
      transform/buttercup-clearedpayment:
        error_mode: ignore
        metric_statements:
          - error_mode: propagate
            statements:
              - replace_all_patterns(resource.attributes, "value", "ButtercupPayments", "payment-clearing-service")
        trace_statements:
          - error_mode: propagate
            statements:
              - replace_all_patterns(span.attributes, "value", "ButtercupPayments", "payment-clearing-service")
      transform/endpoint-fix:
        error_mode: ignore
        trace_statements:
          - error_mode: propagate
            statements:
              - replace_all_patterns(span.attributes, "value", "hipstershop.ProductCatalogService/ListProducts", "finservices.ValidationService/Location")
              - replace_all_patterns(span.attributes, "value", "hipstershop.ProductCatalogService/GetProduct", "finservices.ValidationService/Account")
              - replace_all_patterns(span.attributes, "value", "hipstershop.CartService/AddItem", "finservices.FundsDepositService/DepositTotal")
              - replace_all_patterns(span.attributes, "value", "hipstershop.CartService/GetCart", "finservices.FundsDepositService/GetTotal")
              - replace_all_patterns(span.attributes, "value", "hipstershop.CartService/EmptyCart", "finservices.FundsDepositService/Account")
              - replace_all_patterns(span.attributes, "value", "hipstershop.ShippingService/GetQuote", "finservices.CreditCardService/Account")
              - replace_all_patterns(span.attributes, "value", "hipstershop.ShippingService/ShipOrder", "finservices.CreditCardService/Process")
              - replace_all_patterns(span.attributes, "value", "hipstershop.CheckoutService/PlaceOrder", "finservices.ComplianceCheck/Compliance")
              - replace_all_patterns(span.attributes, "value", "hipstershop.CheckoutService/PlaceOrder", "finservices.ComplianceCheck/Compliance")
              - replace_all_patterns(span.attributes, "value", "hipstershop.PaymentService/Charge", "finservices.WireTransferService/Transfer")
              - replace_all_patterns(span.attributes, "value", "/cart/checkout", "/funds/valid")
              - replace_all_patterns(span.attributes, "value", "hipstershop", "finservices")
              - replace_all_patterns(span.attributes, "value", "buttercup", "external")
              - replace_all_patterns(span.attributes, "value", "Cart", "Deposit")
              - replace_all_patterns(span.attributes, "value", "cart", "deposit")
              - replace_pattern(span.name, "hipstershop.ProductCatalogService/ListProducts", "finservices.ValidationService/Location")
              - replace_pattern(span.name, "hipstershop.ProductCatalogService/GetProduct", "finservices.ValidationService/Account")
              - replace_pattern(span.name, "hipstershop.CartService/AddItem", "finservices.FundsDepositService/DepositTotal")
              - replace_pattern(span.name, "hipstershop.CartService/GetCart", "finservices.FundsDepositService/GetTotal")
              - replace_pattern(span.name, "hipstershop.CartService/EmptyCart", "finservices.FundsDepositService/Account")
              - replace_pattern(span.name, "hipstershop.ShippingService/GetQuote", "finservices.CreditCardService/Account")
              - replace_pattern(span.name, "hipstershop.ShippingService/ShipOrder", "finservices.CreditCardService/Process")
              - replace_pattern(span.name, "hipstershop.CheckoutService/PlaceOrder", "finservices.ComplianceCheck/Compliance")
              - replace_pattern(span.name, "hipstershop.CheckoutService/PlaceOrder", "finservices.ComplianceCheck/Compliance")
              - replace_pattern(span.name, "hipstershop.PaymentService/Charge", "finservices.WireTransferService/Transfer")
              - replace_pattern(span.name, "/cart/checkout", "/funds/valid")
              - replace_pattern(span.name, "buttercup", "external")
              - replace_pattern(span.name, "hipstershop", "finservices")
              - replace_pattern(span.name, "Cart", "Deposit")
              - replace_pattern(span.name, "cart", "deposit")
      transform/logs-fsi:
        error_mode: ignore
        log_statements:
          - error_mode: propagate
            statements:
              - replace_all_patterns(resource.attributes, "value", "ButtercupPayments", "payment-clearing-service")
              - replace_all_patterns(resource.attributes, "value", "emailservice", "new-account-service")
              - replace_all_patterns(resource.attributes, "value", "shippingservice", "credit-card-service")
              - replace_all_patterns(resource.attributes, "value", "productcatalogservice", "validation-service")
              - replace_all_patterns(resource.attributes, "value", "paymentservice", "wire-transfer-service")
              - replace_all_patterns(resource.attributes, "value", "checkoutservice", "compliance-check")
              - replace_all_patterns(resource.attributes, "value", "cartservice", "funds-deposit")
              - replace_all_patterns(resource.attributes, "value", "frontend", "available-funds-check")
              - replace_all_patterns(resource.attributes, "value", "/cart/checkout", "/funds/valid")
              - replace_all_patterns(resource.attributes, "value", "hipstershop", "finservices")
              - replace_all_patterns(resource.attributes, "value", "buttercup", "external")
              - replace_all_patterns(resource.attributes, "value", "Cart", "Deposit")
              - replace_all_patterns(resource.attributes, "value", "cart", "deposit")
              - replace_pattern(log.body, "ButtercupPayments", "payment-clearing-service")
              - replace_pattern(log.body, "emailservice", "new-account-service")
              - replace_pattern(log.body, "shippingservice", "credit-card-service")
              - replace_pattern(log.body, "productcatalogservice", "validation-service")
              - replace_pattern(log.body, "paymentservice", "wire-transfer-service")
              - replace_pattern(log.body, "checkoutservice", "compliance-check")
              - replace_pattern(log.body, "cartservice", "funds-deposit")
              - replace_pattern(log.body, "frontend", "available-funds-check")
              - replace_pattern(log.body, "/cart/checkout", "/funds/valid")
              - replace_pattern(log.body, "hipstershop", "finservices")
              - replace_pattern(log.body, "buttercup", "external")
              - replace_pattern(log.body, "Cart", "Deposit")
              - replace_pattern(log.body, "cart", "deposit")
    service:
      extensions:
      - file_storage
      - health_check
      - k8s_observer
      - zpages
      pipelines:
        logs:
          exporters:
          - splunk_hec/o11y
          - splunk_hec/platform_logs
          - debug
          processors:
          - memory_limiter
          - k8sattributes
          - filter/logs
          - batch
          - resourcedetection
          - resource
          - resource/logs
          - resource/add_environment
          - transform/logs-fsi
          receivers:
          - filelog
          - fluentforward
          - otlp
        logs/entities:
          exporters:
          - otlphttp/entities
          - debug
          processors:
          - memory_limiter
          - batch
          - resourcedetection
          - resource
          - transform/logs-fsi
          receivers:
          - nop
        logs/host:
          exporters:
          - splunk_hec/platform_logs
          - debug
          processors:
          - memory_limiter
          - batch
          - resource
          - resource/add_environment
          - transform/logs-fsi
          receivers:
          - filelog/auth_log
          - filelog/syslog
        metrics:
          exporters:
          - signalfx
          #- debug
          processors:
          - memory_limiter
          - batch
          - resourcedetection
          - resource
          - transform/frontend-available
          - transform/cart-checkdeposit
          - transform/checkout-compliance
          - transform/payment-symbolcheck
          - transform/productcatalog-validation
          - transform/shipping-credit
          - transform/email-newacct
          - transform/buttercup-clearedpayment
          receivers:
          - hostmetrics
          - kubeletstats
          - otlp
          - receiver_creator
          - signalfx
        metrics/agent:
          exporters:
          - signalfx
          processors:
          - memory_limiter
          - batch
          - resource/add_agent_k8s
          - resourcedetection
          - resource
          - resource/add_mode
          receivers:
          - prometheus/agent
        traces:
          exporters:
          - otlphttp
          - signalfx
          #- debug
          processors:
          - memory_limiter
          - k8sattributes
          - batch
          - resourcedetection
          - resource
          - resource/add_environment
          - transform/endpoint-fix
          - transform/frontend-available
          - transform/cart-checkdeposit
          - transform/checkout-compliance
          - transform/payment-symbolcheck
          - transform/productcatalog-validation
          - transform/shipping-credit
          - transform/email-newacct
          - transform/buttercup-clearedpayment
          receivers:
          - otlp
          - jaeger
          - zipkin
      telemetry:
        metrics:
          readers:
          - pull:
              exporter:
                prometheus:
                  host: localhost
                  port: 8889
                  without_scope_info: true
                  without_type_suffix: true
                  without_units: true
        resource:
          service.name: otel-agent
